# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('fileSize', models.IntegerField()),
                ('identifier', models.CharField(default='XXXXXXX', max_length=10)),
                ('name', models.CharField(default='Sound File', max_length=30)),
                ('lyric', models.TextField(blank=True)),
            ],
        ),
    ]
