# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundfile',
            name='fileSizeNoVocals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soundfile',
            name='identifierNoVocals',
            field=models.CharField(default='XXXXXXX_No_Vocal', max_length=20),
        ),
        migrations.AddField(
            model_name='soundfile',
            name='nameNoVocals',
            field=models.CharField(default='No Vocal Sound File', max_length=30),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='fileSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='identifier',
            field=models.CharField(default='XXXXXXX', max_length=20),
        ),
    ]
